apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - media-shared-pv.yaml
  - plex-config-pv.yaml
  - sonarr-config-pv.yaml
  - radarr-config-pv.yaml
  - qbittorrent-config-pv.yaml
  - homeassistant-config-pv.yaml
  - timescaledb-data-pv.yaml
