apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config
  namespace: plex
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-hostpath
  volumeName: plex-config-pv
  resources:
    requests:
      storage: 50Gi
