apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-config
  namespace: plex
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-hostpath
  volumeName: qbittorrent-config-pv
  resources:
    requests:
      storage: 5Gi
