apiVersion: apps/v1
kind: Deployment
metadata:
  name: windmill-server
  namespace: windmill
  labels:
    app: windmill-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: windmill-server
  template:
    metadata:
      labels:
        app: windmill-server
    spec:
      nodeSelector:
        kubernetes.io/hostname: media
      containers:
        - name: windmill-server
          image: ghcr.io/windmill-labs/windmill:main@sha256:cde8e369e80b632e36566a956c88a74cd4fc89beedf35aedf7bdfe8ed5b7c068 # {"$imagepolicy": "flux-system:windmill-main"}
          env:
            - name: MODE
              value: server
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: timescale-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: timescale-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: timescale-secret
                  key: POSTGRES_DB
            - name: POSTGRES_HOST
              value: timescaledb.timescale.svc.cluster.local
            - name: POSTGRES_PORT
              value: "5432"
            - name: DATABASE_URL
              value: postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST):$(POSTGRES_PORT)/$(POSTGRES_DB)
          ports:
            - containerPort: 8000
            - containerPort: 2525
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
