apiVersion: apps/v1
kind: Deployment
metadata:
  name: windmill-worker-reports
  namespace: windmill
  labels:
    app: windmill-worker-reports
spec:
  replicas: 0 # Set to 1 to enable reports worker
  selector:
    matchLabels:
      app: windmill-worker-reports
  template:
    metadata:
      labels:
        app: windmill-worker-reports
    spec:
      containers:
        - name: windmill-worker
          image: ghcr.io/windmill-labs/windmill:main@sha256:1fdcfa2dcf7adf50f4f0577197029e60b0a916853ffb49f0d989ac5022cc3860 # {"$imagepolicy": "flux-system:windmill-main"}
          env:
            - name: MODE
              value: worker
            - name: WORKER_GROUP
              value: reports
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: timescale-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: timescale-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: timescale-secret
                  key: POSTGRES_DB
            - name: POSTGRES_HOST
              value: timescaledb.timescale.svc.cluster.local
            - name: POSTGRES_PORT
              value: "5432"
            - name: DATABASE_URL
              value: postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST):$(POSTGRES_PORT)/$(POSTGRES_DB)
          volumeMounts:
            - mountPath: /var/run/docker.sock
              name: docker-socket
            - mountPath: /tmp/windmill/cache
              name: worker-cache
            - mountPath: /tmp/windmill/logs
              name: worker-logs
          resources:
            limits:
              memory: "3072Mi"
              cpu: "2000m"
            requests:
              memory: "1024Mi"
              cpu: "500m"
      volumes:
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
        - name: worker-cache
          emptyDir: {}
        - name: worker-logs
          emptyDir: {}
