apiVersion: apps/v1
kind: Deployment
metadata:
  name: windmill-worker-native
  namespace: windmill
  labels:
    app: windmill-worker-native
spec:
  replicas: 1
  selector:
    matchLabels:
      app: windmill-worker-native
  template:
    metadata:
      labels:
        app: windmill-worker-native
    spec:
      containers:
        - name: windmill-worker
          image: ghcr.io/windmill-labs/windmill:main@sha256:5cceaf9663db20fc109e324fc1998b191fcc9d5a9b275e7bb6b0378df0ecc3d4 # {"$imagepolicy": "flux-system:windmill-main"}
          env:
            - name: MODE
              value: worker
            - name: WORKER_GROUP
              value: native
            - name: NUM_WORKERS
              value: "8"
            - name: SLEEP_QUEUE
              value: "200"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: timescale-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: timescale-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: timescale-secret
                  key: POSTGRES_DB
            - name: POSTGRES_HOST
              value: timescaledb.timescale.svc.cluster.local
            - name: POSTGRES_PORT
              value: "5432"
            - name: DATABASE_URL
              value: postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST):$(POSTGRES_PORT)/$(POSTGRES_DB)
          volumeMounts:
            - mountPath: /tmp/windmill/cache
              name: worker-cache
            - mountPath: /tmp/windmill/logs
              name: worker-logs
          resources:
            limits:
              memory: "3072Mi"
              cpu: "2000m"
            requests:
              memory: "1024Mi"
              cpu: "500m"
      volumes:
        - name: worker-cache
          emptyDir: {}
        - name: worker-logs
          emptyDir: {}
